import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { canManageResources, enabledOpportunityTypes } from '../utils/providerCapabilities';

const AppHeader = () => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const active = (path: string) => (path === '/provider' ? location.pathname === path : location.pathname.startsWith(path)) ? 'bg-primary-500/15 text-primary-200' : 'text-gray-400 hover:text-white';
  const providerHasOpportunities = enabledOpportunityTypes(user?.providerProfile).length > 0;
  const providerHasResources = canManageResources(user?.providerProfile);
  const signOut = () => { logout(); navigate('/login'); };

  if (!user) return <nav className="sticky top-0 z-30 border-b border-white/10 bg-surface-900/90 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-2 sm:px-6"><Link to="/" className="flex items-center gap-2.5 font-bold text-white"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-primary-500 to-accent-500">⚡</span>TechBridge</Link><div className="flex flex-wrap items-center gap-1"><Link to="/opportunities" className={`rounded-lg px-3 py-2 text-sm ${active('/opportunities')}`}>Opportunities</Link><Link to="/resources" className={`rounded-lg px-3 py-2 text-sm ${active('/resources')}`}>Resources</Link><Link to="/connections" className={`rounded-lg px-3 py-2 text-sm ${active('/connections')}`}>Academic & Alumni</Link><Link to="/login" className="rounded-lg px-3 py-2 text-sm text-gray-300 hover:text-white">Sign in</Link><Link to="/register" className="rounded-lg bg-primary-600 px-3 py-2 text-sm font-semibold text-white hover:bg-primary-500">Get started</Link></div></div></nav>;

  return <nav className="sticky top-0 z-30 border-b border-white/10 bg-surface-900/80 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-2 sm:px-6"><Link to="/dashboard" className="flex items-center gap-2.5 font-bold text-white"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-primary-500 to-accent-500">⚡</span>TechBridge</Link><div className="flex flex-wrap items-center gap-1"><Link to="/impact" className={`rounded-lg px-3 py-2 text-sm ${active('/impact')}`}>Impact</Link><Link to="/connections" className={`rounded-lg px-3 py-2 text-sm ${active('/connections')}`}>Community</Link>{user.role === 'student' && <><Link to="/dashboard" className={`rounded-lg px-3 py-2 text-sm ${active('/dashboard')}`}>Dashboard</Link><Link to="/opportunities" className={`rounded-lg px-3 py-2 text-sm ${active('/opportunities')}`}>Opportunities</Link><Link to="/my-activity" className={`rounded-lg px-3 py-2 text-sm ${active('/my-activity')}`}>My activity</Link><Link to="/resources" className={`rounded-lg px-3 py-2 text-sm ${active('/resources')}`}>Resource Hub</Link><Link to="/student-profile" className={`rounded-lg px-3 py-2 text-sm ${active('/student-profile')}`}>Profile</Link></>}{user.role === 'provider' && <><Link to="/provider" className={`rounded-lg px-3 py-2 text-sm ${active('/provider')}`}>Dashboard</Link>{providerHasOpportunities && <><Link to="/provider/opportunities" className={`rounded-lg px-3 py-2 text-sm ${active('/provider/opportunities')}`}>Listings</Link><Link to="/provider/applications" className={`rounded-lg px-3 py-2 text-sm ${active('/provider/applications')}`}>Applications</Link></>}{providerHasResources && <><Link to="/provider/resources" className={`rounded-lg px-3 py-2 text-sm ${active('/provider/resources')}`}>Resources</Link><Link to="/provider/resource-requests" className={`rounded-lg px-3 py-2 text-sm ${active('/provider/resource-requests')}`}>Requests</Link></>}<Link to="/provider/profile" className={`rounded-lg px-3 py-2 text-sm ${active('/provider/profile')}`}>Profile</Link></>}<span className="hidden px-2 text-sm text-gray-400 lg:block">{user.fullName}</span><button onClick={signOut} className="rounded-lg px-3 py-2 text-sm text-gray-400 hover:bg-white/5 hover:text-white">Sign out</button></div></div></nav>;
};

export default AppHeader;
