import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

import { getMyResourceRequests, getReceivedResourceRequests, updateResourceRequestStatus } from '../api/resourceRequestApi';
import type { ResourceRequest, ResourceRequestStatus } from '../types';

const styles: Record<ResourceRequestStatus, string> = { pending: 'bg-amber-100 text-amber-800', accepted: 'bg-emerald-100 text-emerald-700', rejected: 'bg-red-100 text-red-700', completed: 'bg-primary-100 text-primary-700' };
const humanize = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const resourceOf = (request: ResourceRequest) => typeof request.resourceId === 'string' ? undefined : request.resourceId;
const providerOf = (request: ResourceRequest) => typeof request.providerId === 'string' ? undefined : request.providerId;
const studentOf = (request: ResourceRequest) => typeof request.studentId === 'string' ? undefined : request.studentId;

const MyResourceRequestsPage = () => {
  const [requests, setRequests] = useState<ResourceRequest[]>([]); const [received, setReceived] = useState<ResourceRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { void Promise.all([getMyResourceRequests(), getReceivedResourceRequests()]).then(([outgoing, incoming]) => { setRequests(outgoing); setReceived(incoming); }).catch(() => setError('Unable to load all resource requests.')).finally(() => setLoading(false)); }, []);
  const updateReceived = async (request: ResourceRequest, status: Exclude<ResourceRequestStatus, 'pending'>) => { setError(''); try { const updated = await updateResourceRequestStatus(request._id, status); setReceived((items) => items.map((item) => item._id === request._id ? { ...item, ...updated } : item)); } catch { setError('Unable to update this request.'); } };
  return <div className="min-h-screen bg-surface-50"><main className="max-w-5xl mx-auto px-4 sm:px-6 py-9"><section className="mb-7"><p className="text-primary-600 text-sm font-semibold uppercase tracking-wider">Student dashboard</p><h1 className="text-3xl font-bold text-gray-900 mt-2">Resource requests</h1><p className="text-gray-500 mt-2">Track resources you need and respond when another student asks to use something you listed.</p></section>{error && <div className="mb-5 rounded-xl border border-red-100 bg-red-50 p-4 text-red-700">{error}</div>}{loading ? <p className="text-gray-400">Loading resource requests…</p> : <div className="space-y-9"><RequestSection title="Requests you sent" empty="No resource requests yet." link="/resources" linkLabel="Explore the Resource Hub →" requests={requests} render={(request) => { const resource = resourceOf(request); const provider = providerOf(request); return <article key={request._id} className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h2 className="text-lg font-bold text-gray-900">{resource?.itemName || 'Resource listing'}</h2><p className="text-sm text-gray-500 mt-1">{humanize(request.requestedAccessType)} · {provider?.providerProfile?.organizationName || provider?.fullName || 'Listing owner'}</p>{request.durationOrTerms && <p className="text-sm text-gray-600 mt-2">Requested: {request.durationOrTerms}</p>}<p className="text-xs text-gray-400 mt-2">Sent {new Date(request.createdAt).toLocaleDateString('en-LK')}</p></div><Status status={request.status} /></article>; }} /><RequestSection title="Requests for your shared resources" empty="No one has requested a resource you listed." link="/resources/list" linkLabel="List a resource →" requests={received} render={(request) => { const resource = resourceOf(request); const student = studentOf(request); return <article key={request._id} className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5"><div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4"><div><div className="flex flex-wrap gap-2 items-center"><h2 className="text-lg font-bold text-gray-900">{resource?.itemName || 'Resource listing'}</h2><Status status={request.status} /></div><p className="text-sm text-gray-500 mt-2">Requested by {student?.fullName || 'Student'} · {student?.email || 'No email available'}</p>{request.durationOrTerms && <p className="text-sm text-gray-600 mt-2">Requested terms: {request.durationOrTerms}</p>}{request.message && <p className="mt-2 text-sm text-gray-600">“{request.message}”</p>}</div><RequestActions request={request} update={updateReceived} /></div></article>; }} /></div>}</main></div>;
};

const RequestSection = ({ title, empty, link, linkLabel, requests, render }: { title: string; empty: string; link: string; linkLabel: string; requests: ResourceRequest[]; render: (request: ResourceRequest) => React.ReactNode }) => <section><div className="flex flex-wrap items-end justify-between gap-2 mb-4"><h2 className="text-xl font-bold text-gray-900">{title}</h2><span className="text-sm text-gray-400">{requests.length} request{requests.length === 1 ? '' : 's'}</span></div>{requests.length === 0 ? <div className="rounded-2xl border border-gray-100 bg-white p-7"><p className="text-gray-600">{empty}</p><Link to={link} className="inline-block mt-3 text-primary-600 font-semibold">{linkLabel}</Link></div> : <div className="space-y-4">{requests.map(render)}</div>}</section>;
const Status = ({ status }: { status: ResourceRequestStatus }) => <span className={`self-start rounded-full px-3 py-1.5 text-sm font-semibold ${styles[status]}`}>{humanize(status)}</span>;
const RequestActions = ({ request, update }: { request: ResourceRequest; update: (request: ResourceRequest, status: Exclude<ResourceRequestStatus, 'pending'>) => void }) => request.status === 'pending' ? <div className="flex gap-2"><button onClick={() => update(request, 'accepted')} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white hover:bg-emerald-700">Accept</button><button onClick={() => update(request, 'rejected')} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50">Decline</button></div> : request.status === 'accepted' ? <button onClick={() => update(request, 'completed')} className="rounded-lg bg-gradient-to-r from-primary-500 to-accent-500 px-3 py-2 text-sm font-semibold text-white hover:opacity-90">Mark completed</button> : null;

export default MyResourceRequestsPage;

