import { useEffect, useState, type ChangeEvent, type FormEvent, type ReactNode } from 'react';
import axios from 'axios';
import { Link } from 'react-router-dom';
import AppHeader from '../components/AppHeader';
import { createResource, deleteResource, getMyResources, updateResourceStatus } from '../api/resourceApi';
import { useAuth } from '../hooks/useAuth';
import type { ResourceAccessDetails, ResourceAccessType, ResourceCategory, ResourceCondition, ResourceItemDetails, ResourceListing, ResourceListingFormData } from '../types';
import { enabledResourceAccess, resourceAccessOptions } from '../utils/providerCapabilities';

const categories: Array<{ value: ResourceCategory; label: string }> = [
  { value: 'laptop', label: 'Laptop' }, { value: 'arduino', label: 'Arduino' }, { value: 'raspberry_pi', label: 'Raspberry Pi' },
  { value: 'sensor', label: 'Sensor' }, { value: 'electronic_component', label: 'Electronic component' }, { value: 'dev_board', label: 'Development board' }, { value: 'other', label: 'Other' },
];
const studentTypes: Array<{ value: ResourceAccessType; label: string }> = [{ value: 'borrow', label: 'Borrow' }, { value: 'share', label: 'Share' }, { value: 'donation', label: 'Donation' }];
const financialTypes: ResourceAccessType[] = ['rent', 'installment', 'interest_free', 'sponsorship'];
const readable = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const dateForInput = (daysFromNow: number) => { const date = new Date(); date.setDate(date.getDate() + daysFromNow); return date.toISOString().slice(0, 10); };

const accessDetailsFor = (accessType: ResourceAccessType): ResourceAccessDetails => {
  switch (accessType) {
    case 'borrow': case 'share': return { borrowShare: { borrowDurationDays: 7, pickupLocation: '', returnCondition: '' } };
    case 'rent': return { rent: { pricePerMonth: 0, currency: 'LKR', minRentalMonths: 1 } };
    case 'installment': return { installment: { totalPrice: 0, downPayment: 0, monthlyInstallmentAmount: 0, numberOfMonths: 1, lateFeePolicy: '' } };
    case 'interest_free': return { interestFree: { totalPrice: 0, monthlyInstallmentAmount: 0, numberOfMonths: 1, eligibilityCriteria: [], repaymentStartDate: dateForInput(30), interestRate: 0 } };
    case 'sponsorship': return { sponsorship: { eligibilityCriteria: [], applicationDeadline: dateForInput(30), numberOfUnitsAvailable: 1, sponsorOrganization: '' } };
    case 'donation': return { donation: { itemAgeYears: 1, conditionNotes: '', pickupOrDeliveryMethod: '', claimDeadline: dateForInput(30) } };
  }
};

const itemDetailsFor = (category: ResourceCategory): ResourceItemDetails => {
  switch (category) {
    case 'laptop': return { laptop: { brand: '', model: '', processor: '', processorGeneration: '', ramGb: 8, storageGb: 256, storageType: 'ssd', operatingSystem: '', screenSizeInches: undefined } };
    case 'arduino': return { arduino: { model: '', microcontroller: '', operatingVoltage: '5V', digitalPins: 14, analogPins: 6, usbType: '' } };
    case 'raspberry_pi': return { raspberryPi: { model: '', processor: '', ramGb: 4, storageSupport: 'microSD card', wireless: '' } };
    case 'sensor': return { sensor: { sensorType: '', measuredParameter: '', operatingVoltage: '5V', interface: '' } };
    case 'electronic_component': return { electronicComponent: { componentType: '', valueOrRating: '', packageType: '', voltageRating: '' } };
    case 'dev_board': return { devBoard: { boardModel: '', microcontrollerOrProcessor: '', memory: '', connectivity: '' } };
    case 'other': return { other: { brand: '', model: '', description: '' } };
  }
};

const emptyForm = (accessType: ResourceAccessType): ResourceListingFormData => ({
  itemName: '', category: 'laptop', condition: 'used_good', accessType, quantityAvailable: 1, itemDetails: itemDetailsFor('laptop'), accessDetails: accessDetailsFor(accessType),
});

const Field = ({ label, children }: { label: string; children: ReactNode }) => <label className="block"><span className="field-label">{label}</span>{children}</label>;
const TextInput = ({ value, onChange, type = 'text', required = true, min, placeholder }: { value: string | number; onChange: (value: string) => void; type?: string; required?: boolean; min?: number; placeholder?: string }) => <input required={required} min={min} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="feed-input" placeholder={placeholder} />;

const ResourceListingPage = () => {
  const { user } = useAuth();
  const allowedTypes = (() => {
    if (user?.role === 'student') return studentTypes;
    if (user?.role === 'provider') return resourceAccessOptions.filter((option) => enabledResourceAccess(user.providerProfile).includes(option.value));
    return [...studentTypes, ...resourceAccessOptions];
  })();
  const [form, setForm] = useState<ResourceListingFormData>(() => emptyForm(user?.role === 'provider' ? enabledResourceAccess(user.providerProfile)[0] || 'borrow' : 'borrow'));
  const [listings, setListings] = useState<ResourceListing[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  const load = async () => { setLoading(true); try { setListings(await getMyResources()); } catch { setError('Unable to load your resource listings.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);

  const selectType = (accessType: ResourceAccessType) => setForm((previous) => ({ ...previous, accessType, accessDetails: accessDetailsFor(accessType) }));
  const changeCategory = (category: ResourceCategory) => setForm((previous) => ({ ...previous, category, itemDetails: itemDetailsFor(category) }));
  const patchAccessDetails = (section: keyof ResourceAccessDetails, fields: Record<string, unknown>) => setForm((previous) => ({ ...previous, accessDetails: { [section]: { ...(previous.accessDetails[section] || {}), ...fields } } as ResourceAccessDetails }));
  const patchItemDetails = (section: keyof ResourceItemDetails, fields: Record<string, unknown>) => setForm((previous) => ({ ...previous, itemDetails: { [section]: { ...(previous.itemDetails[section] || {}), ...fields } } as ResourceItemDetails }));
  const criteriaValue = (section: 'interestFree' | 'sponsorship') => form.accessDetails[section]?.eligibilityCriteria.join('\n') || '';
  const setCriteria = (section: 'interestFree' | 'sponsorship', raw: string) => patchAccessDetails(section, { eligibilityCriteria: raw.split('\n').map((line) => line.trim()).filter(Boolean) });
  const isServiceStock = financialTypes.includes(form.accessType);

  const selectImage = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    setError('');
    if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setError('Choose a JPG, PNG, or WebP image.'); event.target.value = ''; return; }
    if (file.size > 2_500_000) { setError('Image must be 2.5 MB or smaller.'); event.target.value = ''; return; }
    const reader = new FileReader();
    reader.onload = () => setForm((previous) => ({ ...previous, imageDataUrl: typeof reader.result === 'string' ? reader.result : undefined }));
    reader.onerror = () => setError('The image could not be read. Please try another file.');
    reader.readAsDataURL(file);
  };

  const submit = async (event: FormEvent) => {
    event.preventDefault(); setSaving(true); setError(''); setNotice('');
    try {
      await createResource({ ...form, ...(isServiceStock ? { condition: undefined } : {}) });
      setNotice('Resource listing published.');
      setForm(emptyForm(allowedTypes[0]?.value || 'borrow'));
      await load();
    } catch (requestError) { setError(axios.isAxiosError(requestError) ? requestError.response?.data?.message || 'Unable to publish listing.' : 'Unable to publish listing.'); }
    finally { setSaving(false); }
  };

  const setStatus = async (listing: ResourceListing, status: 'available' | 'claimed') => {
    try { await updateResourceStatus(listing._id, status); setListings((current) => current.map((item) => item._id === listing._id ? { ...item, status } : item)); setNotice(`Listing marked ${status}.`); }
    catch { setError('Unable to update this listing status.'); }
  };
  const remove = async (id: string) => { if (!window.confirm('Delete this resource listing?')) return; try { await deleteResource(id); setListings((current) => current.filter((listing) => listing._id !== id)); setNotice('Resource listing deleted.'); } catch { setError('Unable to delete this listing.'); } };

  const { borrowShare, rent, installment, interestFree, sponsorship, donation } = form.accessDetails;
  const { laptop, arduino, raspberryPi, sensor, electronicComponent, devBoard, other } = form.itemDetails;

  return <div className="min-h-screen"><AppHeader /><main className="max-w-6xl mx-auto px-4 sm:px-6 py-9">
    <div className="flex items-center justify-between gap-4 mb-7"><div><p className="text-primary-300 text-sm font-semibold mb-2">TECHNICAL RESOURCE ACCESS HUB</p><h1 className="text-3xl font-bold text-white">List a resource</h1><p className="text-gray-400 mt-2">Add a photo, technical specifications, and exact access terms for students.</p></div><Link to="/resources" className="text-sm text-primary-200 hover:text-white">Browse the hub</Link></div>
    {error && <div className="mb-5 p-4 rounded-xl border border-red-500/30 bg-red-500/10 text-red-100">{error}</div>}
    {notice && <div className="mb-5 p-4 rounded-xl border border-emerald-500/30 bg-emerald-500/10 text-emerald-100">{notice}</div>}
    {allowedTypes.length === 0 ? <div className="glass-card p-7"><p className="font-semibold text-white">Technical resource listings are not enabled for this provider.</p><p className="mt-2 text-sm text-gray-400">Enable Technical resources and at least one access pathway in your provider profile.</p><Link to="/provider/profile" className="inline-block mt-4 text-primary-200 font-semibold">Update provider services →</Link></div> : <form onSubmit={submit} className="glass-card p-5 sm:p-7 space-y-7">
      <fieldset><legend className="field-label">1. Access type</legend><div className="flex flex-wrap gap-2">{allowedTypes.map((type) => <button key={type.value} type="button" onClick={() => selectType(type.value)} className={`px-4 py-2.5 rounded-xl text-sm font-medium border ${form.accessType === type.value ? 'bg-primary-500/20 border-primary-400/70 text-white' : 'bg-white/5 border-white/10 text-gray-300 hover:bg-white/10'}`}>{type.label}</button>)}</div>{user?.role === 'student' && <p className="mt-3 text-xs text-gray-500">Students can list resources for borrowing, sharing, or donation only.</p>}</fieldset>
      <section className="space-y-4"><h2 className="font-semibold text-white">2. Basic item details</h2><div className="grid sm:grid-cols-2 gap-4"><Field label="Item name"><TextInput value={form.itemName} onChange={(itemName) => setForm((current) => ({ ...current, itemName }))} placeholder="e.g. Dell Latitude 5420" /></Field><Field label="Category"><select className="feed-input" value={form.category} onChange={(event) => changeCategory(event.target.value as ResourceCategory)}>{categories.map((category) => <option key={category.value} value={category.value}>{category.label}</option>)}</select></Field><Field label="Quantity available"><TextInput type="number" min={1} value={form.quantityAvailable} onChange={(quantityAvailable) => setForm((current) => ({ ...current, quantityAvailable: Number(quantityAvailable) }))} /></Field>{!isServiceStock && <Field label="Condition"><select className="feed-input" value={form.condition || ''} onChange={(event) => setForm((current) => ({ ...current, condition: event.target.value as ResourceCondition }))}><option value="new">New</option><option value="used_good">Used — good</option><option value="used_fair">Used — fair</option></select></Field>}</div></section>

      <section className="rounded-2xl border border-primary-500/20 bg-primary-500/[0.04] p-4 sm:p-5 space-y-4"><div><h2 className="font-semibold text-white">3. {readable(form.category)} specifications</h2><p className="mt-1 text-sm text-gray-400">These fields change for each item category.</p></div>
        {laptop && <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><Field label="Brand"><TextInput value={laptop.brand} onChange={(brand) => patchItemDetails('laptop', { brand })} placeholder="e.g. Dell" /></Field><Field label="Model"><TextInput value={laptop.model} onChange={(model) => patchItemDetails('laptop', { model })} placeholder="e.g. Latitude 5420" /></Field><Field label="Processor"><TextInput value={laptop.processor} onChange={(processor) => patchItemDetails('laptop', { processor })} placeholder="e.g. Intel Core i5" /></Field><Field label="Processor generation"><TextInput value={laptop.processorGeneration} onChange={(processorGeneration) => patchItemDetails('laptop', { processorGeneration })} placeholder="e.g. 11th Gen" /></Field><Field label="RAM capacity (GB)"><TextInput type="number" min={1} value={laptop.ramGb} onChange={(ramGb) => patchItemDetails('laptop', { ramGb: Number(ramGb) })} /></Field><Field label="Storage capacity (GB)"><TextInput type="number" min={1} value={laptop.storageGb} onChange={(storageGb) => patchItemDetails('laptop', { storageGb: Number(storageGb) })} /></Field><Field label="Storage type"><select className="feed-input" value={laptop.storageType} onChange={(event) => patchItemDetails('laptop', { storageType: event.target.value })}><option value="ssd">SSD</option><option value="hdd">HDD</option><option value="emmc">eMMC</option><option value="other">Other</option></select></Field><Field label="Operating system (optional)"><TextInput required={false} value={laptop.operatingSystem || ''} onChange={(operatingSystem) => patchItemDetails('laptop', { operatingSystem })} placeholder="e.g. Windows 11" /></Field><Field label="Screen size, inches (optional)"><TextInput required={false} type="number" min={1} value={laptop.screenSizeInches ?? ''} onChange={(screenSizeInches) => patchItemDetails('laptop', { screenSizeInches: screenSizeInches === '' ? undefined : Number(screenSizeInches) })} /></Field></div>}
        {arduino && <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><Field label="Arduino model"><TextInput value={arduino.model} onChange={(model) => patchItemDetails('arduino', { model })} placeholder="e.g. UNO R3" /></Field><Field label="Microcontroller"><TextInput value={arduino.microcontroller} onChange={(microcontroller) => patchItemDetails('arduino', { microcontroller })} placeholder="e.g. ATmega328P" /></Field><Field label="Operating voltage"><TextInput value={arduino.operatingVoltage} onChange={(operatingVoltage) => patchItemDetails('arduino', { operatingVoltage })} /></Field><Field label="Digital pins"><TextInput type="number" min={0} value={arduino.digitalPins} onChange={(digitalPins) => patchItemDetails('arduino', { digitalPins: Number(digitalPins) })} /></Field><Field label="Analog pins"><TextInput type="number" min={0} value={arduino.analogPins} onChange={(analogPins) => patchItemDetails('arduino', { analogPins: Number(analogPins) })} /></Field><Field label="USB type (optional)"><TextInput required={false} value={arduino.usbType || ''} onChange={(usbType) => patchItemDetails('arduino', { usbType })} placeholder="USB-B / USB-C" /></Field></div>}
        {raspberryPi && <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><Field label="Raspberry Pi model"><TextInput value={raspberryPi.model} onChange={(model) => patchItemDetails('raspberryPi', { model })} placeholder="e.g. Raspberry Pi 4 Model B" /></Field><Field label="Processor"><TextInput value={raspberryPi.processor} onChange={(processor) => patchItemDetails('raspberryPi', { processor })} /></Field><Field label="RAM capacity (GB)"><TextInput type="number" min={1} value={raspberryPi.ramGb} onChange={(ramGb) => patchItemDetails('raspberryPi', { ramGb: Number(ramGb) })} /></Field><Field label="Storage support"><TextInput value={raspberryPi.storageSupport} onChange={(storageSupport) => patchItemDetails('raspberryPi', { storageSupport })} placeholder="e.g. microSD card" /></Field><Field label="Wireless (optional)"><TextInput required={false} value={raspberryPi.wireless || ''} onChange={(wireless) => patchItemDetails('raspberryPi', { wireless })} placeholder="Wi-Fi, Bluetooth" /></Field></div>}
        {sensor && <div className="grid sm:grid-cols-2 gap-4"><Field label="Sensor type"><TextInput value={sensor.sensorType} onChange={(sensorType) => patchItemDetails('sensor', { sensorType })} placeholder="e.g. DHT22" /></Field><Field label="Measured parameter"><TextInput value={sensor.measuredParameter} onChange={(measuredParameter) => patchItemDetails('sensor', { measuredParameter })} placeholder="e.g. Temperature and humidity" /></Field><Field label="Operating voltage"><TextInput value={sensor.operatingVoltage} onChange={(operatingVoltage) => patchItemDetails('sensor', { operatingVoltage })} /></Field><Field label="Interface"><TextInput value={sensor.interface} onChange={(interfaceValue) => patchItemDetails('sensor', { interface: interfaceValue })} placeholder="e.g. I2C, Analog" /></Field></div>}
        {electronicComponent && <div className="grid sm:grid-cols-2 gap-4"><Field label="Component type"><TextInput value={electronicComponent.componentType} onChange={(componentType) => patchItemDetails('electronicComponent', { componentType })} placeholder="e.g. Resistor" /></Field><Field label="Value or rating"><TextInput value={electronicComponent.valueOrRating} onChange={(valueOrRating) => patchItemDetails('electronicComponent', { valueOrRating })} placeholder="e.g. 220Ω, 1/4W" /></Field><Field label="Package type"><TextInput value={electronicComponent.packageType} onChange={(packageType) => patchItemDetails('electronicComponent', { packageType })} placeholder="e.g. Through-hole" /></Field><Field label="Voltage rating (optional)"><TextInput required={false} value={electronicComponent.voltageRating || ''} onChange={(voltageRating) => patchItemDetails('electronicComponent', { voltageRating })} /></Field></div>}
        {devBoard && <div className="grid sm:grid-cols-2 gap-4"><Field label="Board model"><TextInput value={devBoard.boardModel} onChange={(boardModel) => patchItemDetails('devBoard', { boardModel })} placeholder="e.g. ESP32 DevKit V1" /></Field><Field label="Microcontroller / processor"><TextInput value={devBoard.microcontrollerOrProcessor} onChange={(microcontrollerOrProcessor) => patchItemDetails('devBoard', { microcontrollerOrProcessor })} /></Field><Field label="Memory"><TextInput value={devBoard.memory} onChange={(memory) => patchItemDetails('devBoard', { memory })} placeholder="e.g. 4 MB Flash" /></Field><Field label="Connectivity"><TextInput value={devBoard.connectivity} onChange={(connectivity) => patchItemDetails('devBoard', { connectivity })} placeholder="e.g. Wi-Fi, Bluetooth" /></Field></div>}
        {other && <div className="grid sm:grid-cols-2 gap-4"><Field label="Brand (optional)"><TextInput required={false} value={other.brand || ''} onChange={(brand) => patchItemDetails('other', { brand })} /></Field><Field label="Model (optional)"><TextInput required={false} value={other.model || ''} onChange={(model) => patchItemDetails('other', { model })} /></Field><div className="sm:col-span-2"><Field label="Item description"><textarea required className="feed-input min-h-24" value={other.description} onChange={(event) => patchItemDetails('other', { description: event.target.value })} placeholder="Describe the item, its capabilities, and included accessories." /></Field></div></div>}
      </section>

      <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 sm:p-5"><h2 className="font-semibold text-white">4. Item photo <span className="text-sm font-normal text-gray-400">(optional)</span></h2><p className="mt-1 text-sm text-gray-400">JPG, PNG, or WebP up to 2.5 MB. In this MVP, the image is saved with the resource listing.</p><div className="mt-4 flex flex-col gap-4 sm:flex-row sm:items-start"><label className="inline-flex w-fit cursor-pointer items-center rounded-xl border border-primary-400/40 bg-primary-500/10 px-4 py-2.5 text-sm font-semibold text-primary-100 hover:bg-primary-500/20">Choose image<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={selectImage} /></label>{form.imageDataUrl && <div><img src={form.imageDataUrl} alt="Selected resource preview" className="h-28 w-40 rounded-xl border border-white/10 object-cover" /><button type="button" onClick={() => setForm((previous) => ({ ...previous, imageDataUrl: undefined }))} className="mt-2 text-sm text-red-200 hover:text-red-100">Remove image</button></div>}</div></section>

      {(form.accessType === 'borrow' || form.accessType === 'share') && borrowShare && <section className="space-y-4"><h2 className="font-semibold text-white">5. {readable(form.accessType)} terms</h2><div className="grid sm:grid-cols-2 gap-4"><Field label="Maximum duration (days)"><TextInput type="number" min={1} value={borrowShare.borrowDurationDays} onChange={(borrowDurationDays) => patchAccessDetails('borrowShare', { borrowDurationDays: Number(borrowDurationDays) })} /></Field><Field label="Pickup location"><TextInput value={borrowShare.pickupLocation} onChange={(pickupLocation) => patchAccessDetails('borrowShare', { pickupLocation })} placeholder="e.g. Faculty of Technology" /></Field></div><Field label="Return condition notes"><textarea required className="feed-input min-h-24" value={borrowShare.returnCondition} onChange={(event) => patchAccessDetails('borrowShare', { returnCondition: event.target.value })} placeholder="How and in what condition should this be returned?" /></Field></section>}
      {form.accessType === 'rent' && rent && <section className="space-y-4"><h2 className="font-semibold text-white">5. Rental terms</h2><div className="grid sm:grid-cols-2 gap-4"><Field label="Price per month"><TextInput type="number" min={0} value={rent.pricePerMonth} onChange={(pricePerMonth) => patchAccessDetails('rent', { pricePerMonth: Number(pricePerMonth) })} /></Field><Field label="Currency"><TextInput value={rent.currency} onChange={(currency) => patchAccessDetails('rent', { currency: currency.toUpperCase() })} /></Field><Field label="Minimum rental months"><TextInput type="number" min={1} value={rent.minRentalMonths} onChange={(minRentalMonths) => patchAccessDetails('rent', { minRentalMonths: Number(minRentalMonths) })} /></Field><Field label="Security deposit (optional)"><TextInput required={false} type="number" min={0} value={rent.securityDeposit ?? ''} onChange={(securityDeposit) => patchAccessDetails('rent', { securityDeposit: securityDeposit === '' ? undefined : Number(securityDeposit) })} /></Field></div></section>}
      {form.accessType === 'installment' && installment && <section className="space-y-4"><h2 className="font-semibold text-white">5. Installment terms</h2><div className="grid sm:grid-cols-2 gap-4"><Field label="Total price"><TextInput type="number" min={0} value={installment.totalPrice} onChange={(totalPrice) => patchAccessDetails('installment', { totalPrice: Number(totalPrice) })} /></Field><Field label="Down payment"><TextInput type="number" min={0} value={installment.downPayment} onChange={(downPayment) => patchAccessDetails('installment', { downPayment: Number(downPayment) })} /></Field><Field label="Monthly installment"><TextInput type="number" min={0} value={installment.monthlyInstallmentAmount} onChange={(monthlyInstallmentAmount) => patchAccessDetails('installment', { monthlyInstallmentAmount: Number(monthlyInstallmentAmount) })} /></Field><Field label="Number of months"><TextInput type="number" min={1} value={installment.numberOfMonths} onChange={(numberOfMonths) => patchAccessDetails('installment', { numberOfMonths: Number(numberOfMonths) })} /></Field></div><Field label="Late fee policy"><TextInput value={installment.lateFeePolicy} onChange={(lateFeePolicy) => patchAccessDetails('installment', { lateFeePolicy })} placeholder="e.g. No late fee; account reviewed after 7 days" /></Field></section>}
      {form.accessType === 'interest_free' && interestFree && <section className="space-y-4"><div><h2 className="font-semibold text-white">5. Interest-free terms</h2><p className="text-sm text-emerald-200 mt-1">Interest rate is locked at 0%.</p></div><div className="grid sm:grid-cols-2 gap-4"><Field label="Total price"><TextInput type="number" min={0} value={interestFree.totalPrice} onChange={(totalPrice) => patchAccessDetails('interestFree', { totalPrice: Number(totalPrice) })} /></Field><Field label="Monthly installment"><TextInput type="number" min={0} value={interestFree.monthlyInstallmentAmount} onChange={(monthlyInstallmentAmount) => patchAccessDetails('interestFree', { monthlyInstallmentAmount: Number(monthlyInstallmentAmount) })} /></Field><Field label="Number of months"><TextInput type="number" min={1} value={interestFree.numberOfMonths} onChange={(numberOfMonths) => patchAccessDetails('interestFree', { numberOfMonths: Number(numberOfMonths) })} /></Field><Field label="Repayment start date"><TextInput type="date" value={interestFree.repaymentStartDate} onChange={(repaymentStartDate) => patchAccessDetails('interestFree', { repaymentStartDate })} /></Field></div><Field label="Eligibility criteria (one per line)"><textarea required className="feed-input min-h-24" value={criteriaValue('interestFree')} onChange={(event) => setCriteria('interestFree', event.target.value)} placeholder={'ICT student\nValid student ID'} /></Field></section>}
      {form.accessType === 'sponsorship' && sponsorship && <section className="space-y-4"><h2 className="font-semibold text-white">5. Sponsorship terms</h2><div className="grid sm:grid-cols-2 gap-4"><Field label="Sponsor organization"><TextInput value={sponsorship.sponsorOrganization} onChange={(sponsorOrganization) => patchAccessDetails('sponsorship', { sponsorOrganization })} /></Field><Field label="Units available"><TextInput type="number" min={1} value={sponsorship.numberOfUnitsAvailable} onChange={(numberOfUnitsAvailable) => patchAccessDetails('sponsorship', { numberOfUnitsAvailable: Number(numberOfUnitsAvailable) })} /></Field><Field label="Application deadline"><TextInput type="date" value={sponsorship.applicationDeadline} onChange={(applicationDeadline) => patchAccessDetails('sponsorship', { applicationDeadline })} /></Field></div><Field label="Eligibility criteria (one per line)"><textarea required className="feed-input min-h-24" value={criteriaValue('sponsorship')} onChange={(event) => setCriteria('sponsorship', event.target.value)} placeholder={'Financial need\nCurrently enrolled student'} /></Field></section>}
      {form.accessType === 'donation' && donation && <section className="space-y-4"><h2 className="font-semibold text-white">5. Donation details</h2><div className="grid sm:grid-cols-2 gap-4"><Field label="Item age (years)"><TextInput type="number" min={0} value={donation.itemAgeYears} onChange={(itemAgeYears) => patchAccessDetails('donation', { itemAgeYears: Number(itemAgeYears) })} /></Field><Field label="Claim deadline"><TextInput type="date" value={donation.claimDeadline} onChange={(claimDeadline) => patchAccessDetails('donation', { claimDeadline })} /></Field><Field label="Pickup or delivery method"><TextInput value={donation.pickupOrDeliveryMethod} onChange={(pickupOrDeliveryMethod) => patchAccessDetails('donation', { pickupOrDeliveryMethod })} placeholder="Pickup / delivery / both" /></Field></div><Field label="Condition notes"><textarea required className="feed-input min-h-24" value={donation.conditionNotes} onChange={(event) => patchAccessDetails('donation', { conditionNotes: event.target.value })} placeholder="Describe item condition and included accessories." /></Field></section>}
      {financialTypes.includes(form.accessType) && <p className="rounded-xl border border-amber-400/25 bg-amber-500/10 px-4 py-3 text-sm text-amber-100">TechBridge does not provide loans or financing. These arrangements are offered directly by verified providers, subject to their own terms.</p>}
      <button disabled={saving} className="px-5 py-3 rounded-xl font-semibold text-white bg-gradient-to-r from-primary-500 to-accent-500 disabled:opacity-50">{saving ? 'Publishing...' : 'Publish listing'}</button>
    </form>}
    <section className="mt-10"><h2 className="text-xl font-bold text-white mb-4">Your listings</h2>{loading ? <p className="text-gray-400">Loading your listings...</p> : listings.length === 0 ? <div className="glass-card p-6 text-gray-400">You have not listed any resources yet.</div> : <div className="grid md:grid-cols-2 gap-4">{listings.map((listing) => <article key={listing._id} className="glass-card p-5"><div className="flex justify-between gap-3">{listing.imageDataUrl && <img src={listing.imageDataUrl} alt="" className="h-14 w-14 rounded-lg object-cover border border-white/10" />}<div className="mr-auto"><h3 className="font-semibold text-white">{listing.itemName}</h3><p className="mt-1 text-xs text-gray-400">{readable(listing.accessType)} · {listing.quantityAvailable} units</p></div><select value={listing.status} onChange={(event) => void setStatus(listing, event.target.value as 'available' | 'claimed')} className="feed-input !w-auto !py-1.5 text-sm"><option value="available">Available</option><option value="claimed">Claimed</option></select></div><div className="mt-4 flex items-center justify-between"><span className={`text-xs px-2 py-1 rounded ${listing.providerOrgVerified ? 'bg-emerald-500/15 text-emerald-200' : 'bg-white/10 text-gray-300'}`}>{listing.providerOrgVerified ? 'Verified provider' : 'Community listing'}</span><button onClick={() => void remove(listing._id)} className="text-sm text-red-200 hover:text-red-100">Delete</button></div></article>)}</div>}</section>
  </main></div>;
};

export default ResourceListingPage;
